framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: true
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    assets:
        json_manifest_path: '%kernel.project_dir%/web/build/manifest.json'
    trusted_hosts: ~
    fragments: ~
    php_errors:
        log: true
