version: '2'

services:
  data:
    image: alpine
    volumes:
      - .:/code

  console:
    build: docker/php-console
    volumes_from:
      - data
    volumes:
      - ./docker/conf/php.ini:/usr/local/etc/php/php.ini:ro
    depends_on:
      - docker
    environment:
      - DOCKER_HOST=tcp://docker:2375

  docker:
    image: docker:17-dind
    volumes_from:
      - data
    privileged: true
